### ISSUE TITLE
[question] Linked containers ?

### ISSUE THREAD

**Issue by ShagoY** [circa10a/ouroboros#33]
Hello :)
One of the problems on watchtower is the way it handles "--net=container:XXXX". (See: [https://github.com/v2tec/watchtower/issues/188](https://github.com/v2tec/watchtower/issues/188)).

I can't find any information on "Linked Containers", how does "ouroboros" behave in this case?

Regards.

**Comment by circa10a** [comment]
Hi @ShagoY,

Ouroboros recreates the container with the same `HostConfig` properties as before including links and docker networks.

One thing I have noticed before about links, both with watchtower and ouroboros, is that if the container with the link option is restarted after it's dependency, the dependency may not come up in time which results in `Cannot link to a non running container`, which then requires the docker daemon to be restarted.

To avoid this, docker networks are definitely preferred and are recommended since [links may be removed](https://docs.docker.com/network/links/) and also will never encounter the error mentioned above.

Here is an example after instantiating 2 containers connected to the network `example` and then running ouroboros in the background.

```
❯ docker run -d --restart unless-stopped  --name testName4 -v $(pwd):/tmp --net example -p 1235:1236 alpine:3.7 tail -f /dev/null

❯ docker run -d --restart unless-stopped  --name testName4 -v $(pwd):/tmp  --net example -p 1235:1236 alpine:3.7 tail -f /dev/null

❯ docker exec -it testName5 sh
/ # ping testName4
PING testName4 (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.288 ms
64 bytes from 172.18.0.3: seq=1 ttl=64 time=0.128 ms
```

I'll update the docs to reflect the this :)

**Comment by ShagoY** [comment]
Sorry for the delay... But I still have a problem when the "vpn" container is updated.
The rutorrent container loses the connection for the reasons you mentioned above but i don't use "link".

Here my docker-compose : 


```
services:
    vpn:
        image: dperson/openvpn-client
        restart: always
        container_name: vpn
        cap_add:
        - net_admin
        devices:
        - /dev/net/tun

    rutorrent:
        image: xataz/rtorrent-rutorrent:latest
        container_name: rutorrent
        restart: always
        network_mode: "service:vpn"
        depends_on:
        - vpn
        
networks:
  default:
```

What's wrong ?
