### ISSUE TITLE
Invalid URL 'h': No schema supplied. Perhaps you meant http://h?

### ISSUE THREAD

**Issue by reinierkors** [circa10a/ouroboros#76]
Running docker-compose configuration:

> [INFO] 2019-01-09 00:10:11 Ouroboros configuration: {'url': 'unix://var/run/docker.sock', 'interval': 300, 'monitor': [], 'ignore': [], 'loglevel': 'info', 'run_once': False, 'cleanup': 'true', 'keep_tag': False, 'metrics_addr': '0.0.0.0', 'metrics_port': 8000, 'webhook_urls': 'https://discordapp.com/api/webhooks/123/example-dfdsj34223424__234easdASj/slack'}
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'h': No schema supplied. Perhaps you meant http://h?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 't': No schema supplied. Perhaps you meant http://t?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 't': No schema supplied. Perhaps you meant http://t?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'p': No schema supplied. Perhaps you meant http://p?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 's': No schema supplied. Perhaps you meant http://s?
> [ERROR] 2019-01-09 00:15:25 No connection adapters were found for ':'
> [ERROR] 2019-01-09 00:15:25 Invalid URL '/': No schema supplied. Perhaps you meant http:///?
> [ERROR] 2019-01-09 00:15:25 Invalid URL '/': No schema supplied. Perhaps you meant http:///?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'd': No schema supplied. Perhaps you meant http://d?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'i': No schema supplied. Perhaps you meant http://i?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 's': No schema supplied. Perhaps you meant http://s?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'c': No schema supplied. Perhaps you meant http://c?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'o': No schema supplied. Perhaps you meant http://o?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'r': No schema supplied. Perhaps you meant http://r?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'd': No schema supplied. Perhaps you meant http://d?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'a': No schema supplied. Perhaps you meant http://a?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'p': No schema supplied. Perhaps you meant http://p?
> [ERROR] 2019-01-09 00:15:25 Invalid URL 'p': No schema supplied. Perhaps you meant http://p?

Using docker-compose:
```
  ouroboros:
    container_name: ouroboros
    restart: unless-stopped
    image: circa10a/ouroboros
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - UID=1000
      - GID=1000
      - WEBHOOK_URLS=https://discordapp.com/api/webhooks/123/example-dfdsj34223424__234easdASj/slack
      - CLEANUP=true
```
